### PR TITLE
Refine code with ES6

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by M-Reimer** [comment]
I've never worked with ES6, so please give me some time to understand what you did here.
What does the "async" in front of "function" do?
I'm not that happy about the idea that everyone adds his own "Copyright"-Line with pull requests. Your whole contact data gets added to your commit anyway. Maybe I should place a "CONTRIBUTORS" file for contributors to add their contact data...

**Comment by yfdyh000** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

Free to modify it while merge.

**Comment by yfdyh000** [comment]
I made a fork. https://github.com/yfdyh000/undoclosetab

**Comment by M-Reimer** [comment]
I had a closer look and this looks all pretty great! Thanks for your work!
What did you mean with:

> // stripping "lastModified"

Seems like your "GetLastClosedTabs()" function doesn't actually return "tabs" but sessions, right?

**Comment by yfdyh000** [comment]
> Seems like your "GetLastClosedTabs()" function doesn't actually return "tabs" but sessions, right?

Yes, I think this makes it more complete.

**Comment by M-Reimer** [comment]
I currently can't think of a case where we could need access to the "session" object, but I'll merge your pull request unchanged anyway. Maybe I'll change that back in future to return tabs again. Or at least document this in a comment.

Thank you very much for your great help! There are really nice things possible with javascript that I didn't know so far.

**Comment by M-Reimer** [comment]
Oh and about your fork: Nice work, but I would prefer to keep my "building" in the simple "Makefile". That's what I already have on my machine.

**Comment by M-Reimer** [comment]
Do you think you can create pull-requests for your other changes? I would grab from your repository otherwise, if this is OK. You did some very impressive updates and I would like to create a new release based on this within the next days. Thanks in advance.

**Comment by yfdyh000** [comment]
I suspect that some of my changes are not satisfied for everyone (such as the icon support detection, it can be replaced with min 56 directly) and I welcome you to merge commIts directly into your repo on locally.

**Pull request merged**
