### PR TITLE
Add zh_TW language

### PR DESCRIPTION
**Pull request by zhtw2013**
Add zh_TW language

### CODE REVIEW

**Comment by zhtw2013** [comment]
@M-Reimer Hello！！！！

**Comment by M-Reimer** [comment]
Hi. No need to rush :P I'm very busy recently.

Thank you very much for your translation. I'll merge your change now, but please give me some more time to create a new release. I think in about one or two additional days your translation will ship via AMO.

**Comment by zhtw2013** [comment]
OK，Thank you!

**Comment by M-Reimer** [comment]
4.1.2 has been reviewed by Mozilla. Should be available shortly.

**Pull request merged**
